name: flutter_tinkoff_sdk
description: A new flutter plugin project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  json_serializable: ^6.1.4
  build_runner: ^2.1.7

flutter:
 
  plugin:
    platforms:
      android:
        package: com.lvznd.tinkoffsdk.flutter_tinkoff_sdk
        pluginClass: TinkoffAcquiringSdkPlugin
      ios:
        pluginClass: FlutterTinkoffSDkPlugin
Ø
 